services:

  postgres:
    image: postgres:16-alpine
    container_name: shope2door-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: shope2door
      POSTGRES_PASSWORD: shope2door
      POSTGRES_DB: shope2door

    ports:
      - "5435:5432"

    volumes:
      - shope2door_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U shope2door -d shope2door"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: shope2door-redis
    restart: unless-stopped

    ports:
      - "6380:6380"

    volumes:
      - shope2door_redis_data:/data

    command: redis-server --appendonly yes

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 10


volumes:

  shope2door_postgres_data:

  shope2door_redis_data: